# Generated by Django 5.2.1 on 2025-06-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[
                    ("UZS", "Uzs"),
                    ("USD", "Usd"),
                    ("EUR", "Eur"),
                    ("RUB", "Rub"),
                ],
                default="USD",
                max_length=10,
            ),
        ),
    ]
