# Generated by Django 5.2.1 on 2025-08-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardinganswer",
            name="degree",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="onboardinganswer",
            name="graduation_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="onboardinganswer",
            name="interests",
            field=models.TextField(blank=True, null=True),
        ),
    ]
