# Generated by Django 5.2.1 on 2025-08-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="university",
            options={
                "verbose_name": "University",
                "verbose_name_plural": "Universities",
            },
        ),
    ]
