# Generated by Django 5.2.1 on 2025-06-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="trainers",
            new_name="tutors",
        ),
    ]
